import type { SQLiteDatabase } from 'expo-sqlite';
import type { TaskRecord } from './types';
import * as FileSystem from 'expo-file-system/legacy';

const schema = `CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY NOT NULL, prompt TEXT NOT NULL, status TEXT NOT NULL, resolution TEXT NOT NULL, duration INTEGER NOT NULL, seed TEXT, images_json TEXT, audios_json TEXT, video_url TEXT, local_uri TEXT, thumbnail_url TEXT, download_state TEXT NOT NULL DEFAULT 'IDLE', download_error TEXT, download_progress REAL, gallery_uri TEXT, export_state TEXT NOT NULL DEFAULT 'NOT_REQUESTED', export_error TEXT, exported_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, started_at INTEGER, execution_duration INTEGER, workflow_id TEXT, workflow_version TEXT, workflow_hash TEXT, adapter_id TEXT, adapter_version TEXT, input_json TEXT, sync_error TEXT, last_sync_at INTEGER);`;
export type TaskPageCursor = { createdAt: number; id: string };
export type TaskPageOptions = { limit?: number; cursor?: TaskPageCursor; status?: TaskRecord['status']; query?: string };
export function createTaskRepository(db: SQLiteDatabase) {
  db.execSync(schema);
  db.execSync('CREATE INDEX IF NOT EXISTS idx_tasks_created_id ON tasks(created_at DESC, id DESC); CREATE INDEX IF NOT EXISTS idx_tasks_status_updated_id ON tasks(status, updated_at DESC, id DESC);');
  for (const statement of ['ALTER TABLE tasks ADD COLUMN download_state TEXT NOT NULL DEFAULT \'IDLE\'', 'ALTER TABLE tasks ADD COLUMN download_error TEXT', 'ALTER TABLE tasks ADD COLUMN download_progress REAL', 'ALTER TABLE tasks ADD COLUMN gallery_uri TEXT', 'ALTER TABLE tasks ADD COLUMN export_state TEXT NOT NULL DEFAULT \'NOT_REQUESTED\'', 'ALTER TABLE tasks ADD COLUMN export_error TEXT', 'ALTER TABLE tasks ADD COLUMN exported_at INTEGER', 'ALTER TABLE tasks ADD COLUMN started_at INTEGER', 'ALTER TABLE tasks ADD COLUMN execution_duration INTEGER', 'ALTER TABLE tasks ADD COLUMN workflow_id TEXT', 'ALTER TABLE tasks ADD COLUMN workflow_version TEXT', 'ALTER TABLE tasks ADD COLUMN workflow_hash TEXT', 'ALTER TABLE tasks ADD COLUMN adapter_id TEXT', 'ALTER TABLE tasks ADD COLUMN adapter_version TEXT', 'ALTER TABLE tasks ADD COLUMN input_json TEXT', 'ALTER TABLE tasks ADD COLUMN sync_error TEXT', 'ALTER TABLE tasks ADD COLUMN last_sync_at INTEGER']) { try { db.execSync(statement); } catch {} }
  const map = (r: any): TaskRecord => ({ id: r.id, prompt: r.prompt, status: r.status, resolution: r.resolution, duration: Number(r.duration), seed: r.seed || undefined, workflowId: r.workflow_id || undefined, workflowVersion: r.workflow_version || undefined, workflowContentHash: r.workflow_hash || undefined, adapterId: r.adapter_id || undefined, adapterVersion: r.adapter_version || undefined, inputSnapshot: r.input_json ? JSON.parse(r.input_json) : undefined, images: r.images_json ? JSON.parse(r.images_json) : undefined, audios: r.audios_json ? JSON.parse(r.audios_json) : undefined, videoUrl: r.video_url || undefined, localUri: r.local_uri || undefined, thumbnailUrl: r.thumbnail_url || undefined, downloadState: r.download_state || (r.local_uri ? 'DOWNLOADED' : 'IDLE'), downloadError: r.download_error || undefined, downloadProgress: r.download_progress == null ? undefined : Number(r.download_progress), galleryUri: r.gallery_uri || undefined, exportState: r.export_state || 'NOT_REQUESTED', exportError: r.export_error || undefined, exportedAt: r.exported_at == null ? undefined : Number(r.exported_at), createdAt: Number(r.created_at), updatedAt: Number(r.updated_at), startedAt: r.started_at == null ? undefined : Number(r.started_at), executionDuration: r.execution_duration == null ? undefined : Number(r.execution_duration), syncError: r.sync_error || undefined, lastSyncAt: r.last_sync_at == null ? undefined : Number(r.last_sync_at) });
  return {
    async upsert(t: TaskRecord) { db.runSync('INSERT INTO tasks (id,prompt,status,resolution,duration,seed,images_json,audios_json,video_url,local_uri,thumbnail_url,download_state,download_error,download_progress,gallery_uri,export_state,export_error,exported_at,created_at,updated_at,started_at,execution_duration,workflow_id,workflow_version,workflow_hash,adapter_id,adapter_version,input_json,sync_error,last_sync_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET prompt=excluded.prompt,status=excluded.status,resolution=excluded.resolution,duration=excluded.duration,seed=excluded.seed,images_json=excluded.images_json,audios_json=excluded.audios_json,video_url=excluded.video_url,local_uri=excluded.local_uri,thumbnail_url=excluded.thumbnail_url,download_state=excluded.download_state,download_error=excluded.download_error,download_progress=excluded.download_progress,gallery_uri=excluded.gallery_uri,export_state=excluded.export_state,export_error=excluded.export_error,exported_at=excluded.exported_at,created_at=excluded.created_at,updated_at=excluded.updated_at,started_at=excluded.started_at,execution_duration=excluded.execution_duration,workflow_id=excluded.workflow_id,workflow_version=excluded.workflow_version,workflow_hash=excluded.workflow_hash,adapter_id=excluded.adapter_id,adapter_version=excluded.adapter_version,input_json=excluded.input_json,sync_error=excluded.sync_error,last_sync_at=excluded.last_sync_at', t.id, t.prompt, t.status, t.resolution, t.duration, t.seed ?? null, t.images ? JSON.stringify(t.images) : null, t.audios ? JSON.stringify(t.audios) : null, t.videoUrl ?? null, t.localUri ?? null, t.thumbnailUrl ?? null, t.downloadState ?? (t.localUri ? 'DOWNLOADED' : 'IDLE'), t.downloadError ?? null, t.downloadProgress ?? null, t.galleryUri ?? null, t.exportState ?? 'NOT_REQUESTED', t.exportError ?? null, t.exportedAt ?? null, t.createdAt, t.updatedAt, t.startedAt ?? null, t.executionDuration ?? null, t.workflowId ?? null, t.workflowVersion ?? null, t.workflowContentHash ?? null, t.adapterId ?? null, t.adapterVersion ?? null, t.inputSnapshot ? JSON.stringify(t.inputSnapshot) : null, t.syncError ?? null, t.lastSyncAt ?? null); },
    async list() { return (db.getAllSync<any>('SELECT * FROM tasks ORDER BY created_at DESC') ?? []).map(map); },
    async listPage(options: TaskPageOptions = {}) {
      const limit = Math.max(1, Math.min(100, options.limit ?? 30));
      const query = options.query?.trim().toLowerCase();
      const cursor = options.cursor;
      const rows = db.getAllSync<any>('SELECT * FROM tasks WHERE (? IS NULL OR status = ?) AND (? IS NULL OR lower(prompt) LIKE ? OR lower(id) LIKE ?) AND (? IS NULL OR created_at < ? OR (created_at = ? AND id < ?)) ORDER BY created_at DESC, id DESC LIMIT ?', options.status ?? null, options.status ?? null, query ?? null, query ? `%${query}%` : null, query ? `%${query}%` : null, cursor?.createdAt ?? null, cursor?.createdAt ?? null, cursor?.createdAt ?? null, cursor?.id ?? null, limit + 1) ?? [];
      const hasMore = rows.length > limit;
      const items = rows.slice(0, limit).map(map);
      const last = items[items.length - 1];
      return { items, nextCursor: hasMore && last ? { createdAt: last.createdAt, id: last.id } : undefined };
    },
    async listUpdatedSince(watermark: number, limit = 200) { return (db.getAllSync<any>('SELECT * FROM tasks WHERE updated_at > ? ORDER BY updated_at ASC, id ASC LIMIT ?', watermark, Math.max(1, Math.min(1000, limit))) ?? []).map(map); },
    async listActive() { return (db.getAllSync<any>("SELECT * FROM tasks WHERE status IN ('QUEUED','RUNNING','UNKNOWN') ORDER BY updated_at ASC, id ASC") ?? []).map(map); },
    async listMediaPending() { return (db.getAllSync<any>("SELECT * FROM tasks WHERE status = 'SUCCESS' AND (video_url IS NOT NULL OR local_uri IS NOT NULL OR gallery_uri IS NOT NULL) AND (download_state <> 'DOWNLOADED' OR export_state IN ('QUEUED','EXPORTING')) ORDER BY updated_at ASC, id ASC") ?? []).map(map); },
    async remove(id: string) { const rows = db.getAllSync<any>('SELECT local_uri, thumbnail_url FROM tasks WHERE id = ? LIMIT 1', id); db.runSync('DELETE FROM tasks WHERE id = ?', id); for (const row of rows) { for (const uri of [row.local_uri, row.thumbnail_url]) { if (uri) { try { await FileSystem.deleteAsync(uri, { idempotent: true }); } catch {} } } } },
  };
}
