import type { SQLiteDatabase } from 'expo-sqlite';
import type { TaskRecord } from './types';
import * as FileSystem from 'expo-file-system/legacy';

const schema = `CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY NOT NULL, prompt TEXT NOT NULL, status TEXT NOT NULL, resolution TEXT NOT NULL, duration INTEGER NOT NULL, seed TEXT, images_json TEXT, audios_json TEXT, video_url TEXT, local_uri TEXT, thumbnail_url TEXT, download_state TEXT NOT NULL DEFAULT 'IDLE', download_error TEXT, download_progress REAL, gallery_uri TEXT, export_state TEXT NOT NULL DEFAULT 'NOT_REQUESTED', export_error TEXT, exported_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, started_at INTEGER, execution_duration INTEGER, workflow_id TEXT, workflow_version TEXT, workflow_hash TEXT, adapter_id TEXT, adapter_version TEXT, input_json TEXT);`;
export function createTaskRepository(db: SQLiteDatabase) {
  db.execSync(schema);
  for (const statement of ['ALTER TABLE tasks ADD COLUMN download_state TEXT NOT NULL DEFAULT \'IDLE\'', 'ALTER TABLE tasks ADD COLUMN download_error TEXT', 'ALTER TABLE tasks ADD COLUMN download_progress REAL', 'ALTER TABLE tasks ADD COLUMN gallery_uri TEXT', 'ALTER TABLE tasks ADD COLUMN export_state TEXT NOT NULL DEFAULT \'NOT_REQUESTED\'', 'ALTER TABLE tasks ADD COLUMN export_error TEXT', 'ALTER TABLE tasks ADD COLUMN exported_at INTEGER', 'ALTER TABLE tasks ADD COLUMN started_at INTEGER', 'ALTER TABLE tasks ADD COLUMN execution_duration INTEGER', 'ALTER TABLE tasks ADD COLUMN workflow_id TEXT', 'ALTER TABLE tasks ADD COLUMN workflow_version TEXT', 'ALTER TABLE tasks ADD COLUMN workflow_hash TEXT', 'ALTER TABLE tasks ADD COLUMN adapter_id TEXT', 'ALTER TABLE tasks ADD COLUMN adapter_version TEXT', 'ALTER TABLE tasks ADD COLUMN input_json TEXT']) { try { db.execSync(statement); } catch {} }
  const map = (r: any): TaskRecord => ({ id: r.id, prompt: r.prompt, status: r.status, resolution: r.resolution, duration: Number(r.duration), seed: r.seed || undefined, workflowId: r.workflow_id || undefined, workflowVersion: r.workflow_version || undefined, workflowContentHash: r.workflow_hash || undefined, adapterId: r.adapter_id || undefined, adapterVersion: r.adapter_version || undefined, inputSnapshot: r.input_json ? JSON.parse(r.input_json) : undefined, images: r.images_json ? JSON.parse(r.images_json) : undefined, audios: r.audios_json ? JSON.parse(r.audios_json) : undefined, videoUrl: r.video_url || undefined, localUri: r.local_uri || undefined, thumbnailUrl: r.thumbnail_url || undefined, downloadState: r.download_state || (r.local_uri ? 'DOWNLOADED' : 'IDLE'), downloadError: r.download_error || undefined, downloadProgress: r.download_progress == null ? undefined : Number(r.download_progress), galleryUri: r.gallery_uri || undefined, exportState: r.export_state || 'NOT_REQUESTED', exportError: r.export_error || undefined, exportedAt: r.exported_at == null ? undefined : Number(r.exported_at), createdAt: Number(r.created_at), updatedAt: Number(r.updated_at), startedAt: r.started_at == null ? undefined : Number(r.started_at), executionDuration: r.execution_duration == null ? undefined : Number(r.execution_duration) });
  return {
    async upsert(t: TaskRecord) { db.runSync('INSERT OR REPLACE INTO tasks (id,prompt,status,resolution,duration,seed,images_json,audios_json,video_url,local_uri,thumbnail_url,download_state,download_error,download_progress,gallery_uri,export_state,export_error,exported_at,created_at,updated_at,started_at,execution_duration) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', t.id, t.prompt, t.status, t.resolution, t.duration, t.seed ?? null, t.images ? JSON.stringify(t.images) : null, t.audios ? JSON.stringify(t.audios) : null, t.videoUrl ?? null, t.localUri ?? null, t.thumbnailUrl ?? null, t.downloadState ?? (t.localUri ? 'DOWNLOADED' : 'IDLE'), t.downloadError ?? null, t.downloadProgress ?? null, t.galleryUri ?? null, t.exportState ?? 'NOT_REQUESTED', t.exportError ?? null, t.exportedAt ?? null, t.createdAt, t.updatedAt, t.startedAt ?? null, t.executionDuration ?? null); },
    async list() { return (db.getAllSync<any>('SELECT * FROM tasks ORDER BY created_at DESC') ?? []).map(map); },
    async remove(id: string) { const rows = db.getAllSync<any>('SELECT local_uri, thumbnail_url FROM tasks WHERE id = ? LIMIT 1', id); db.runSync('DELETE FROM tasks WHERE id = ?', id); for (const row of rows) { for (const uri of [row.local_uri, row.thumbnail_url]) { if (uri) { try { await FileSystem.deleteAsync(uri, { idempotent: true }); } catch {} } } } },
  };
}
