import { memo, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppIcon } from '../ui/icons';
import { COLORS, SPACING } from '../ui/theme';
import { exportStatusLabel } from '../gallery/presentation';
import { formatTaskCreatedAt, formatTaskStatus, getTaskTiming } from './presentation';
import type { TaskCard } from './taskCard';
export const TaskCardRow = memo(function TaskCardRow({ item, busy, onDownload, onExport, onRemove, onOpen }: {
 item: TaskCard; busy: boolean; onDownload(item: TaskCard): void; onExport(item: TaskCard): void; onRemove(id: string): void; onOpen(id: string): void;
}) { const exportLabel = exportStatusLabel(item); const terminalSuccess = item.status === 'SUCCESS' || item.status === 'PARTIAL_SUCCESS'; const needsExport = item.downloadState === 'DOWNLOADED' && item.exportState !== 'EXPORTED'; const exportActionLabel = item.exportState === 'EXPORT_FAILED' ? '重试保存到系统相册' : '保存到系统相册'; const mediaBusy = busy || item.downloadState === 'ENQUEUED' || item.downloadState === 'DOWNLOADING' || item.exportState === 'QUEUED' || item.exportState === 'EXPORTING'; return <View style={styles.card}><View style={styles.header}><Text numberOfLines={1} style={styles.id}>{item.id}</Text><Text style={[styles.status, item.status === 'SUCCESS' ? styles.success : item.status === 'FAILED' ? styles.failure : item.status === 'RUNNING' ? styles.running : undefined]}>{formatTaskStatus(item.status)}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="查看任务详情" onPress={() => onOpen(item.id)}><Text numberOfLines={3} style={styles.prompt}>{item.prompt}</Text></Pressable><Text style={styles.meta}>{item.resolution} · {item.duration}s</Text><TaskTiming task={item} />{item.syncError ? <Text style={styles.syncError}>{item.syncError}</Text> : null}{item.downloadState && terminalSuccess ? <View style={styles.downloadRow}><Text style={styles.downloadText}>{item.downloadState === 'DOWNLOADED' ? (exportLabel || '已下载到应用') : item.downloadState === 'DOWNLOAD_FAILED' ? item.downloadError || '下载失败' : `${item.downloadState}${item.downloadProgress ? ` ${Math.round(item.downloadProgress * 100)}%` : ''}`}</Text>{item.downloadState !== 'DOWNLOADED' && <Pressable accessibilityRole="button" accessibilityLabel={item.downloadState === 'DOWNLOAD_FAILED' ? '重试下载' : '下载视频'} accessibilityState={{ disabled: mediaBusy, busy: mediaBusy }} disabled={mediaBusy} onPress={() => void onDownload(item)} style={[styles.action, mediaBusy && styles.disabled]}><AppIcon name={item.downloadState === 'DOWNLOAD_FAILED' ? 'refresh' : 'download'} size={17} color={COLORS.primaryActive} /><Text style={styles.actionText}>{item.downloadState === 'DOWNLOAD_FAILED' ? '重试' : '下载'}</Text></Pressable>}{needsExport && <Pressable accessibilityRole="button" accessibilityLabel={exportActionLabel} accessibilityState={{ disabled: mediaBusy, busy: mediaBusy }} disabled={mediaBusy} onPress={() => void onExport(item)} style={[styles.action, mediaBusy && styles.disabled]}><AppIcon name={item.exportState === 'EXPORT_FAILED' ? 'refresh' : 'download'} size={17} color={COLORS.primaryActive} /><Text style={styles.actionText}>{item.exportState === 'EXPORT_FAILED' ? '重试保存' : '保存到相册'}</Text></Pressable>}</View> : null}<Pressable disabled={mediaBusy} onPress={() => Alert.alert('移除任务', '仅移除本地记录和应用内副本。已保存到系统相册的视频会保留。', [{ text: '取消' }, { text: '移除', style: 'destructive', onPress: () => void onRemove(item.id) }])} style={[styles.remove, mediaBusy && styles.disabled]}><Text style={styles.removeText}>移除记录</Text></Pressable></View>; });
const TaskTiming = memo(function TaskTiming({ task }: { task: TaskCard }) {
  const active = task.status === 'QUEUED' || task.status === 'RUNNING' || task.status === 'UNKNOWN';
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    if (!active) return;
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, [active]);
  const timing = useMemo(() => getTaskTiming(task, now), [task, now]);
  return <View style={styles.timing}><Text style={styles.timingText}>创建 {formatTaskCreatedAt(task.createdAt)}</Text><Text style={styles.timingText}>排队 {timing.queued}</Text><Text style={styles.timingText}>执行 {timing.running}</Text></View>;
});


const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background, padding: SPACING.xl }, heading: { position: 'relative', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingRight: 100 }, headingActions: { position: 'absolute', right: 0, top: 0, flexDirection: 'row', gap: 8, flexShrink: 0 }, title: { color: COLORS.text, fontSize: 29, fontWeight: '800' }, subtitle: { color: COLORS.textMuted, marginTop: 7, lineHeight: 20 }, syncStatus: { color: COLORS.primaryActive, marginTop: 5, fontSize: 11 }, syncError: { color: COLORS.danger, marginTop: 8, fontSize: 11 }, refresh: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border }, refreshing: { borderColor: COLORS.primaryActive, opacity: 0.8 }, monitoring: { borderColor: COLORS.primaryActive }, list: { gap: SPACING.md, paddingTop: SPACING.xl, paddingBottom: 130 }, empty: { color: COLORS.textSubtle, textAlign: 'center', marginTop: 64 }, card: { backgroundColor: COLORS.surface, borderColor: COLORS.border, borderWidth: 1, borderRadius: 16, padding: SPACING.lg }, header: { flexDirection: 'row', justifyContent: 'space-between', gap: SPACING.md }, id: { color: COLORS.primaryActive, fontSize: 11, flex: 1, fontFamily: 'monospace' }, status: { color: '#fbbf24', fontSize: 11, fontWeight: '800' }, running: { color: COLORS.primaryActive }, success: { color: COLORS.success }, failure: { color: COLORS.danger }, prompt: { color: COLORS.text, marginTop: 11, lineHeight: 20 }, meta: { color: COLORS.textSubtle, marginTop: 11, fontSize: 12 }, timing: { gap: 4, marginTop: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: COLORS.border }, timingText: { color: COLORS.textMuted, fontSize: 12, fontFamily: 'monospace' }, downloadRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 13, paddingTop: 11, borderTopWidth: 1, borderTopColor: COLORS.border }, downloadText: { color: COLORS.textMuted, fontSize: 12, flex: 1 }, action: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 8, backgroundColor: COLORS.primarySoft }, actionText: { color: COLORS.primaryActive, fontSize: 12, fontWeight: '700' }, remove: { alignSelf: 'flex-end', marginTop: 12 }, removeText: { color: COLORS.textSubtle, fontSize: 12 }, disabled: { opacity: 0.5 } });
