import { StyleSheet } from 'react-native';
import { COLORS, LIGHT_PROMPT_COLORS } from '../ui/theme';

export const sentStyles = {
  sentAttachments: { gap: 7, marginBottom: 7 },
  sentAttachment: { width: 54, height: 54, borderRadius: 11 },
};

export const markdownStyles = {
  paragraph: {
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 15,
    lineHeight: 23,
    marginTop: 2,
    marginBottom: 7,
  },
  h1: { color: LIGHT_PROMPT_COLORS.ink },
  h2: { color: LIGHT_PROMPT_COLORS.ink },
  h3: { color: LIGHT_PROMPT_COLORS.ink },
  codeBlock: {
    backgroundColor: '#F0EFEA',
    borderRadius: 12,
    padding: 12,
    color: LIGHT_PROMPT_COLORS.ink,
  },
  code: { backgroundColor: '#F0EFEA', color: LIGHT_PROMPT_COLORS.ink },
};
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: LIGHT_PROMPT_COLORS.background },
  header: {
    minHeight: 62,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: LIGHT_PROMPT_COLORS.background,
  },
  headerButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: LIGHT_PROMPT_COLORS.surface,
  },
  headerTitleWrap: { flex: 1, paddingHorizontal: 10 },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 1.3,
    color: LIGHT_PROMPT_COLORS.muted,
    fontWeight: '700',
  },
  title: {
    marginTop: 2,
    fontSize: 17,
    fontWeight: '700',
    color: LIGHT_PROMPT_COLORS.ink,
  },
  body: { flex: 1, flexDirection: 'row' },
  sidebar: {
    width: 264,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: LIGHT_PROMPT_COLORS.line,
    padding: 14,
  },
  conversation: { flex: 1, maxWidth: 820, alignSelf: 'center', width: '100%' },
  notice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginHorizontal: 16,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: '#FFF4D6',
  },
  noticeText: { flex: 1, color: '#8A5A00', fontSize: 12, lineHeight: 17 },
  timeline: { flex: 1 },
  timelineContent: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 18 },
  runningIndicator: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: LIGHT_PROMPT_COLORS.surface,
  },
  runningIndicatorCompact: { alignSelf: 'flex-start', marginTop: 8, marginBottom: 8 },
  runIssue: {
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5C4BC',
    backgroundColor: '#FFF4F1',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  runIssueText: {
    flex: 1,
    color: '#8B3528',
    fontSize: 13,
    lineHeight: 18,
  },
  runIssueAction: {
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3D9D2',
  },
  runIssueActionText: { color: '#743026', fontSize: 12, fontWeight: '700' },
  runningDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: LIGHT_PROMPT_COLORS.accent,
  },
  runningText: { color: LIGHT_PROMPT_COLORS.muted, fontSize: 13, fontWeight: '600' },
  empty: { paddingTop: 26, paddingBottom: 12 },
  emptyHeading: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  emptyMark: {
    width: 38,
    height: 38,
    borderRadius: 15,
    backgroundColor: LIGHT_PROMPT_COLORS.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    color: LIGHT_PROMPT_COLORS.ink,
    flex: 1,
    fontSize: 24,
    lineHeight: 34,
    fontWeight: '600',
  },
  emptySubtitle: {
    marginTop: 12,
    color: LIGHT_PROMPT_COLORS.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  inspirationRail: { gap: 14, paddingTop: 24, paddingBottom: 8, paddingRight: 16 },
  inspirationCard: { borderRadius: 26, padding: 20, overflow: 'hidden', justifyContent: 'space-between' },
  inspirationPressed: { opacity: 0.85, transform: [{ scale: 0.98 }] },
  inspirationCategory: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  inspirationCategoryText: { color: '#F3F2EB', fontSize: 13, fontWeight: '600' },
  inspirationArtwork: { height: 112, marginVertical: 16, alignItems: 'center', justifyContent: 'center' },
  artOrb: { position: 'absolute', width: 100, height: 100, borderRadius: 50, opacity: 0.45, right: 12, top: 0 },
  artFrame: { width: 132, height: 84, borderRadius: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.5)', backgroundColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center' },
  artCaption: { position: 'absolute', left: 0, bottom: 0, color: '#F3F2EB', fontSize: 9, letterSpacing: 2 },
  inspirationTitle: { color: '#FFFFFF', fontSize: 20, lineHeight: 29, fontWeight: '500', minHeight: 58, textAlign: 'center' },
  inspirationCta: { marginTop: 18, minHeight: 44, paddingVertical: 10, paddingHorizontal: 18, borderRadius: 24, borderBottomRightRadius: 6, backgroundColor: '#FFFFFF', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  inspirationCtaText: { color: LIGHT_PROMPT_COLORS.ink, fontSize: 14, fontWeight: '600' },
  suggestions: { width: '100%', marginTop: 16, gap: 2 },
  suggestion: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 14,
    overflow: 'hidden',
  },
  suggestionArrow: { color: LIGHT_PROMPT_COLORS.ink, fontSize: 22 },
  suggestionText: { flex: 1, color: LIGHT_PROMPT_COLORS.ink, fontSize: 15, lineHeight: 22 },
  userRow: { alignItems: 'flex-end', marginVertical: 8 },
  userBubble: {
    maxWidth: '84%',
    paddingHorizontal: 15,
    paddingVertical: 11,
    borderRadius: 18,
    borderBottomRightRadius: 5,
    backgroundColor: '#ECEBE6',
  },
  userText: { color: LIGHT_PROMPT_COLORS.ink, fontSize: 15, lineHeight: 22 },
  userMention: {
    paddingHorizontal: 3,
    borderRadius: 6,
    backgroundColor: '#E9E7E1',
    color: LIGHT_PROMPT_COLORS.ink,
    fontWeight: '600',
  },
  userMentionImage: { width: 18, height: 18, borderRadius: 4 },
  assistantRow: { flexDirection: 'row', gap: 9, marginVertical: 10 },
  assistantMark: {
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: LIGHT_PROMPT_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assistantContent: { flex: 1, minWidth: 0 },
  assistantCopy: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    minHeight: 30,
    paddingHorizontal: 8,
    marginTop: 2,
    borderRadius: 10,
  },
  assistantCopyText: {
    color: LIGHT_PROMPT_COLORS.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  toolTimeline: {
    marginTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: LIGHT_PROMPT_COLORS.line,
  },
  toolSummary: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  toolChevron: { color: LIGHT_PROMPT_COLORS.muted, fontSize: 20 },
  toolSummaryText: { color: LIGHT_PROMPT_COLORS.muted, fontSize: 12 },
  toolSteps: { paddingBottom: 8 },
  toolStep: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    flexWrap: 'wrap',
  },
  stepDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#68856D' },
  stepDotFailed: { backgroundColor: '#B35E53' },
  stepName: { color: LIGHT_PROMPT_COLORS.ink, fontSize: 12, flex: 1 },
  stepStatus: { color: LIGHT_PROMPT_COLORS.muted, fontSize: 11 },
  stepSummary: {
    width: '100%',
    paddingLeft: 13,
    color: LIGHT_PROMPT_COLORS.muted,
    fontSize: 11,
  },
  promptCard: {
    marginTop: 12,
    padding: 15,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: LIGHT_PROMPT_COLORS.line,
    backgroundColor: LIGHT_PROMPT_COLORS.surface,
  },
  promptCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  promptCardEyebrow: {
    color: LIGHT_PROMPT_COLORS.muted,
    fontSize: 10,
    letterSpacing: 1,
    fontWeight: '700',
  },
  promptCardTitle: {
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 3,
  },
  promptText: {
    marginTop: 13,
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 14,
    lineHeight: 21,
  },
  promptActions: { flexDirection: 'row', gap: 8, marginTop: 15 },
  secondaryAction: {
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: LIGHT_PROMPT_COLORS.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  secondaryActionText: {
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 12,
    fontWeight: '600',
  },
  primaryAction: {
    flex: 1,
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: LIGHT_PROMPT_COLORS.ink,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  primaryActionText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  primaryActionArrow: { color: '#FFFFFF', fontSize: 16 },
  composerDock: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 7 },
  composerActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingBottom: 8 },
  composerAction: { minHeight: 44, maxWidth: '100%', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 24, backgroundColor: '#ECEFEC' },
  composerActionPressed: { backgroundColor: COLORS.primarySoft },
  composerActionText: { flexShrink: 1, fontSize: 13, lineHeight: 18, fontWeight: '600', color: LIGHT_PROMPT_COLORS.ink },
  versionCount: { minWidth: 20, textAlign: 'center', paddingHorizontal: 5, borderRadius: 5, backgroundColor: COLORS.primarySoft, color: COLORS.primary, fontSize: 12, lineHeight: 20, fontWeight: '700' },
  composer: {
    padding: 12,
    borderRadius: 30,
    shadowColor: '#24362E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
    backgroundColor: LIGHT_PROMPT_COLORS.surface,
  },
  composerRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  inputArea: {
    minHeight: 64,
    maxHeight: 120,
    position: 'relative',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  toolbarSpacer: { flex: 1 },
  addButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F2F4F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    maxHeight: 120,
    minHeight: 36,
    paddingTop: 8,
    paddingBottom: 7,
    color: LIGHT_PROMPT_COLORS.ink,
    paddingHorizontal: 6,
    fontSize: 17,
    lineHeight: 24,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: LIGHT_PROMPT_COLORS.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendDisabled: { backgroundColor: '#ECEBE6' },
  attachments: { paddingHorizontal: 2, paddingBottom: 8, gap: 8 },
  attachment: { width: 72, height: 72, paddingTop: 8, paddingRight: 8 },
  attachmentImage: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: '#ECEBE6',
  },
  attachmentLoading: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: '#ECEBE6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: { color: LIGHT_PROMPT_COLORS.muted, fontSize: 9 },
  removeAttachment: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 44,
    height: 44,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
  },
  removeAttachmentBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: LIGHT_PROMPT_COLORS.surface,
    backgroundColor: LIGHT_PROMPT_COLORS.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,.78)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImage: { width: '92%', height: '78%' },
  history: { flex: 1 },
  historySearch: {
    height: 40,
    borderRadius: 12,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: LIGHT_PROMPT_COLORS.surface,
  },
  searchInput: {
    flex: 1,
    marginLeft: 7,
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 13,
  },
  newHistory: {
    minHeight: 40,
    marginTop: 10,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: LIGHT_PROMPT_COLORS.line,
  },
  newHistoryText: {
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 13,
    fontWeight: '600',
  },
  historyList: { marginTop: 13 },
  groupLabel: {
    marginTop: 10,
    marginBottom: 5,
    color: LIGHT_PROMPT_COLORS.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  historyItem: {
    minHeight: 55,
    paddingHorizontal: 10,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  historyItemActive: {
    backgroundColor: '#ECEBE6',
    borderWidth: 1,
    borderColor: LIGHT_PROMPT_COLORS.line,
  },
  historyItemMain: { flex: 1, minWidth: 0 },
  historyTitle: {
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 13,
    fontWeight: '600',
  },
  historyMeta: { color: LIGHT_PROMPT_COLORS.muted, fontSize: 10, marginTop: 3 },
  more: { color: LIGHT_PROMPT_COLORS.muted, fontSize: 12 },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(20,20,18,.3)',
  },
  mentionBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(20,20,18,.3)',
  },
  mentionSheet: {
    maxHeight: '72%',
    minHeight: '32%',
    padding: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: LIGHT_PROMPT_COLORS.background,
  },
  mentionList: { marginTop: 4 },
  mentionRow: {
    minHeight: 64,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mentionImage: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: '#ECEBE6',
  },
  mentionImagePlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECEBE6',
  },
  mentionName: { flex: 1, color: LIGHT_PROMPT_COLORS.ink, fontSize: 15 },
  mentionEmpty: { alignItems: 'center', justifyContent: 'center', gap: 14, paddingVertical: 36 },
  mentionEmptyText: { color: LIGHT_PROMPT_COLORS.muted, fontSize: 15 },
  mentionAddButton: {
    minHeight: 42,
    paddingHorizontal: 16,
    borderRadius: 21,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: '#ECEBE6',
  },
  mentionAddText: { color: LIGHT_PROMPT_COLORS.ink, fontSize: 14, fontWeight: '600' },
  sheet: {
    maxHeight: '80%',
    minHeight: '45%',
    padding: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: LIGHT_PROMPT_COLORS.background,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: LIGHT_PROMPT_COLORS.line,
    marginBottom: 12,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 7,
  },
  sheetTitle: {
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 20,
    fontWeight: '700',
  },
  renameBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: 'rgba(20,20,18,.28)',
  },
  renameKeyboardSurface: { flex: 1 },
  renameCard: {
    width: '100%',
    maxWidth: 420,
    padding: 18,
    borderRadius: 20,
    backgroundColor: LIGHT_PROMPT_COLORS.background,
  },
  renameTitle: {
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 17,
    fontWeight: '700',
  },
  renameInput: {
    marginTop: 14,
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: LIGHT_PROMPT_COLORS.line,
    color: LIGHT_PROMPT_COLORS.ink,
  },
  renameActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 9,
    marginTop: 14,
  },
  renameCancel: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 11,
    backgroundColor: '#ECEBE6',
  },
  renameCancelText: {
    color: LIGHT_PROMPT_COLORS.ink,
    fontSize: 13,
    fontWeight: '600',
  },
  renameConfirm: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 11,
    backgroundColor: LIGHT_PROMPT_COLORS.ink,
  },
  renameConfirmText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
});
