import React, { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { readSettings, saveSettings } from '../../src/settings/storage';
import { prepareSettingsForSave } from '../../src/settings/validation';
import { AppIcon } from '../../src/ui/icons';
import { COLORS, SPACING } from '../../src/ui/theme';
import { taskStore } from '../../src/tasks/sync';
import { migrateDownloadedVideos } from '../../src/tasks/media';

type Settings = Awaited<ReturnType<typeof readSettings>>;
export default function SettingsScreen() {
  const [values, setValues] = useState<Settings>({ token: '', llmEndpoint: 'https://api.openai.com/v1', llmModel: 'gpt-4o-mini', llmApiKey: '', llmTimeoutSeconds: '600', llmMaxRetries: '2', autoExportToGallery: true, keepPrivateCopy: true });
  const [saving, setSaving] = useState(false);
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const [pendingMigrationCount, setPendingMigrationCount] = useState(0);
  const [migrating, setMigrating] = useState(false);
  useEffect(() => {
    void readSettings().then(setValues);
    void taskStore.list().then((tasks) => setPendingMigrationCount(tasks.filter((task) => task.localUri && task.exportState !== 'EXPORTED').length)).catch(() => undefined);
  }, []);
  const update = (key: keyof Settings, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); try { await saveSettings(prepareSettingsForSave(values)); Alert.alert('已保存', '配置已使用 Android Keystore 加密存储。'); } catch (error) { Alert.alert('保存失败', error instanceof Error ? error.message : '无法保存设置'); } finally { setSaving(false); } };
  const migrate = async () => {
    if (migrating) return;
    setMigrating(true);
    try {
      const tasks = await taskStore.list();
      const result = await migrateDownloadedVideos(tasks, { policy: { autoExportToGallery: values.autoExportToGallery, keepPrivateCopy: values.keepPrivateCopy }, onUpdate: async (_task, patch) => { await taskStore.upsert({ ..._task, ...patch }); } });
      setPendingMigrationCount(0);
      Alert.alert('迁移完成', `已保存 ${result.exported} 个，失败 ${result.failed} 个`);
    } catch (error) {
      Alert.alert('迁移失败', error instanceof Error ? error.message : '历史视频迁移失败');
    } finally { setMigrating(false); }
  };
  return <ScrollView style={styles.container} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View><Text style={styles.title}>系统设置</Text><Text style={styles.subtitle}>配置 AutoDL 连接令牌与 Prompt 助手 LLM。所有密钥仅保存在本机安全存储中。</Text></View>
    <View style={styles.card}><View style={styles.cardHeading}><AppIcon name="key" size={20} color={COLORS.primaryActive} /><Text style={styles.cardTitle}>AutoDL ComfyUI Token</Text></View><Text style={styles.help}>用于提交任务、查询状态和自动下载结果。Token 不会写入源码或上传到第三方。</Text><Field label="ComfyUI Token" value={values.token} secure placeholder="输入 AutoDL ComfyUI 分组 Token" onChangeText={(text) => update('token', text)} /></View>
    <View style={styles.card}><View style={styles.cardHeading}><AppIcon name="smart_toy" size={20} color={COLORS.primaryActive} /><Text style={styles.cardTitle}>Prompt 助手 LLM</Text></View><Text style={styles.help}>Agent Harness、官方 H3 skills、工具调用和会话全部在本机运行。此处仅配置外部 OpenAI-compatible LLM API。</Text><Field label="LLM API 地址" value={values.llmEndpoint} placeholder="https://api.openai.com/v1" autoCapitalize="none" keyboardType="url" onChangeText={(text) => update('llmEndpoint', text)} /><Field label="LLM 模型" value={values.llmModel} placeholder="gpt-4o-mini" autoCapitalize="none" onChangeText={(text) => update('llmModel', text)} /><Field label="LLM API Key" value={values.llmApiKey} secure placeholder="仅保存在 Android Keystore" autoCapitalize="none" onChangeText={(text) => update('llmApiKey', text)} /><Pressable accessibilityRole="button" accessibilityLabel="切换 LLM 高级设置" onPress={() => setAdvancedOpen((open) => !open)} style={styles.advancedToggle}><Text style={styles.advancedToggleText}>高级设置</Text><AppIcon name={advancedOpen ? 'expand_less' : 'expand_more'} size={20} color={COLORS.textMuted} /></Pressable>{advancedOpen ? <View style={styles.advancedPanel}><Text style={styles.advancedHint}>超时是单次请求最长等待时间；重试次数越高，总等待时间和 API 调用次数也会增加。</Text><Field label="请求超时（秒）" value={values.llmTimeoutSeconds} placeholder="600" keyboardType="number-pad" onChangeText={(text) => update('llmTimeoutSeconds', text)} /><Field label="最大重试次数" value={values.llmMaxRetries} placeholder="2" keyboardType="number-pad" onChangeText={(text) => update('llmMaxRetries', text)} /></View> : null}</View>
    <View style={styles.card}><View style={styles.cardHeading}><AppIcon name="movie_filter" size={20} color={COLORS.primaryActive} /><Text style={styles.cardTitle}>存储与导出</Text></View><View style={styles.settingRow}><View style={styles.settingCopy}><Text style={styles.settingLabel}>自动保存到系统相册</Text><Text style={styles.help}>下载完成后保存到系统相册 / Movies / AutoDL-H3</Text></View><Switch accessibilityLabel="自动保存到系统相册" value={values.autoExportToGallery} onValueChange={(value) => update('autoExportToGallery', value)} trackColor={{ false: COLORS.border, true: COLORS.primaryActive }} thumbColor={COLORS.text} /></View><Text style={styles.location}>保存位置：系统相册 / Movies / AutoDL-H3</Text><View style={styles.settingRow}><View style={styles.settingCopy}><Text style={styles.settingLabel}>保留应用内副本</Text><Text style={styles.help}>关闭后仅在相册保存成功时删除应用内视频</Text></View><Switch accessibilityLabel="保留应用内副本" value={values.keepPrivateCopy} onValueChange={(value) => update('keepPrivateCopy', value)} trackColor={{ false: COLORS.border, true: COLORS.primaryActive }} thumbColor={COLORS.text} /></View><Pressable accessibilityRole="button" accessibilityLabel="将已有下载保存到相册" disabled={migrating || pendingMigrationCount === 0} onPress={() => void migrate()} style={[styles.migrateButton, (migrating || pendingMigrationCount === 0) && styles.disabled]}><Text style={styles.migrateText}>{migrating ? '迁移中…' : `将已有下载保存到相册（${pendingMigrationCount} 个待处理）`}</Text></Pressable></View>
    <View style={styles.card}><View style={styles.cardHeading}><AppIcon name="info" size={20} color={COLORS.primaryActive} /><Text style={styles.cardTitle}>工作流说明</Text></View><Text style={styles.infoLine}>工作流：MiniMax H3 图像与音频生视频 v2（15s）</Text><Text style={styles.infoLine}>ID：minimax_h3_image_audio_to_video_v2_15s</Text><Text style={styles.infoLine}>参考素材：最多 9 张图片、3 段音频，单个文件 50MB</Text><Text style={styles.infoLine}>下载目录：Movies/AutoDL-H3（同时保留应用私有缓存）</Text></View>
    <Pressable disabled={saving} onPress={() => void save()} style={[styles.saveButton, saving && styles.disabled]}><AppIcon name="save" size={20} color={COLORS.text} /><Text style={styles.saveText}>{saving ? '保存中…' : '保存设置'}</Text></Pressable>
  </ScrollView>;
}
function Field({ label, secure, ...props }: { label: string; secure?: boolean } & React.ComponentProps<typeof TextInput>) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} secureTextEntry={secure} placeholderTextColor={COLORS.textSubtle} style={styles.input} /></View>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, content: { padding: SPACING.xl, paddingBottom: 150, gap: SPACING.lg }, title: { color: COLORS.text, fontSize: 30, fontWeight: '800' }, subtitle: { color: COLORS.textMuted, fontSize: 14, lineHeight: 21, marginTop: SPACING.sm }, card: { backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: 16, padding: SPACING.lg, gap: SPACING.md }, cardHeading: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm }, cardTitle: { color: COLORS.text, fontSize: 16, fontWeight: '800' }, help: { color: COLORS.textMuted, fontSize: 12, lineHeight: 18 }, field: { gap: SPACING.xs }, label: { color: COLORS.textMuted, fontSize: 11, fontWeight: '700', letterSpacing: 0.4 }, input: { color: COLORS.text, backgroundColor: COLORS.background, borderWidth: 1, borderColor: COLORS.border, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, fontSize: 14 }, advancedToggle: { minHeight: 40, borderTopWidth: 1, borderTopColor: COLORS.border, paddingTop: SPACING.sm, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, advancedToggleText: { color: COLORS.text, fontSize: 14, fontWeight: '700' }, advancedPanel: { gap: SPACING.md }, advancedHint: { color: COLORS.textMuted, fontSize: 12, lineHeight: 18 }, infoLine: { color: COLORS.textMuted, fontSize: 12, lineHeight: 19 }, settingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: SPACING.md }, settingCopy: { flex: 1, gap: 4 }, settingLabel: { color: COLORS.text, fontSize: 14, fontWeight: '700' }, location: { color: COLORS.primaryActive, fontSize: 12 }, migrateButton: { minHeight: 44, borderRadius: 11, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 }, migrateText: { color: COLORS.text, fontSize: 13, fontWeight: '700', textAlign: 'center' }, saveButton: { minHeight: 54, borderRadius: 14, backgroundColor: COLORS.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: SPACING.sm }, saveText: { color: COLORS.text, fontSize: 16, fontWeight: '800' }, disabled: { opacity: 0.5 } });
