import { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppIcon } from '../../src/ui/icons';
import { COLORS, SPACING } from '../../src/ui/theme';
import { taskStore, syncTasks } from '../../src/tasks/sync';
import { downloadTask } from '../../src/tasks/download';
import type { TaskRecord } from '../../src/tasks/types';

export default function TasksScreen() {
  const [tasks, setTasks] = useState<TaskRecord[]>([]);
  const [syncing, setSyncing] = useState(false);
  const load = useCallback(async () => { setTasks(await taskStore.list()); setSyncing(true); try { setTasks(await syncTasks()); } catch {} finally { setSyncing(false); } }, []);
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 10000); return () => clearInterval(timer); }, [load]);
  const remove = async (id: string) => { await taskStore.remove(id); setTasks((items) => items.filter((item) => item.id !== id)); };
  const retry = async (task: TaskRecord) => { try { const updated = await downloadTask({ ...task, downloadState: 'IDLE', downloadError: undefined }, { onUpdate: async (patch) => { const value = { ...task, ...patch }; await taskStore.upsert(value); setTasks((items) => items.map((item) => item.id === task.id ? value : item)); } }); setTasks((items) => items.map((item) => item.id === task.id ? updated : item)); } catch (error) { Alert.alert('下载失败', error instanceof Error ? error.message : '视频下载失败'); } };
  return <View style={styles.container}><View style={styles.heading}><View><Text style={styles.title}>任务队列</Text><Text style={styles.subtitle}>任务状态、下载进度和本地媒体统一管理。</Text></View><Pressable accessibilityRole="button" accessibilityLabel="刷新任务" onPress={() => void load()} style={styles.refresh}><AppIcon name="refresh" size={20} color={syncing ? COLORS.primaryActive : COLORS.textMuted} /></Pressable></View><FlatList data={tasks} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>{syncing ? '正在同步任务…' : '暂无任务'}</Text>} renderItem={({ item }) => <View style={styles.card}><View style={styles.header}><Text numberOfLines={1} style={styles.id}>{item.id}</Text><Text style={[styles.status, item.status === 'SUCCESS' ? styles.success : item.status === 'FAILED' ? styles.failure : undefined]}>{item.status}</Text></View><Text numberOfLines={3} style={styles.prompt}>{item.prompt}</Text><Text style={styles.meta}>{item.resolution} · {item.duration}s</Text>{item.downloadState && item.status === 'SUCCESS' ? <View style={styles.downloadRow}><Text style={styles.downloadText}>{item.downloadState === 'DOWNLOADED' ? '已下载并生成首帧' : item.downloadState === 'DOWNLOAD_FAILED' ? item.downloadError || '下载失败' : `${item.downloadState}${item.downloadProgress ? ` ${Math.round(item.downloadProgress * 100)}%` : ''}`}</Text>{item.downloadState !== 'DOWNLOADED' && <Pressable onPress={() => void retry(item)} style={styles.action}><AppIcon name={item.downloadState === 'DOWNLOAD_FAILED' ? 'refresh' : 'download'} size={17} color={COLORS.primaryActive} /><Text style={styles.actionText}>{item.downloadState === 'DOWNLOAD_FAILED' ? '重试' : '下载'}</Text></Pressable>}</View> : null}<Pressable onPress={() => Alert.alert('移除任务', '仅移除本地记录，不会撤销服务端任务。', [{ text: '取消' }, { text: '移除', style: 'destructive', onPress: () => void remove(item.id) }])} style={styles.remove}><Text style={styles.removeText}>移除记录</Text></Pressable></View>} /></View>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background, padding: SPACING.xl }, heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, title: { color: COLORS.text, fontSize: 29, fontWeight: '800' }, subtitle: { color: COLORS.textMuted, marginTop: 7, lineHeight: 20 }, refresh: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border }, list: { gap: SPACING.md, paddingTop: SPACING.xl, paddingBottom: 130 }, empty: { color: COLORS.textSubtle, textAlign: 'center', marginTop: 64 }, card: { backgroundColor: COLORS.surface, borderColor: COLORS.border, borderWidth: 1, borderRadius: 16, padding: SPACING.lg }, header: { flexDirection: 'row', justifyContent: 'space-between', gap: SPACING.md }, id: { color: COLORS.primaryActive, fontSize: 11, flex: 1, fontFamily: 'monospace' }, status: { color: '#fbbf24', fontSize: 11, fontWeight: '800' }, success: { color: COLORS.success }, failure: { color: COLORS.danger }, prompt: { color: COLORS.text, marginTop: 11, lineHeight: 20 }, meta: { color: COLORS.textSubtle, marginTop: 11, fontSize: 12 }, downloadRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 13, paddingTop: 11, borderTopWidth: 1, borderTopColor: COLORS.border }, downloadText: { color: COLORS.textMuted, fontSize: 12, flex: 1 }, action: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 8, backgroundColor: COLORS.primarySoft }, actionText: { color: COLORS.primaryActive, fontSize: 12, fontWeight: '700' }, remove: { alignSelf: 'flex-end', marginTop: 12 }, removeText: { color: COLORS.textSubtle, fontSize: 12 } });
